In [1]:
# import necessary libraries
import pandas as pd
import numpy as np

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

In [2]:
# Read Starbucks store locations into a dataframe
file = "Resources/locations.csv"
locations_df = pd.read_csv(file)
locations_df.head()

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
0,Starbucks,47370-257954,"Meritxell, 96",Licensed,"Av. Meritxell, 96",Andorra la Vella,7,AD,AD500,376818720,GMT+1:00 Europe/Andorra,1.53,42.51
1,Starbucks,22331-212325,Ajman Drive Thru,Licensed,"1 Street 69, Al Jarf",Ajman,AJ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,55.47,25.42
2,Starbucks,47089-256771,Dana Mall,Licensed,Sheikh Khalifa Bin Zayed St.,Ajman,AJ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,55.47,25.39
3,Starbucks,22126-218024,Twofour 54,Licensed,Al Salam Street,Abu Dhabi,AZ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,54.38,24.48
4,Starbucks,17127-178586,Al Ain Tower,Licensed,"Khaldiya Area, Abu Dhabi Island",Abu Dhabi,AZ,AE,NaN,NaN,GMT+04:00 Asia/Dubai,54.54,24.51

In [3]:
# filter on US Starbucks locations
us_locations_df = locations_df[locations_df['Country']=='US']
us_locations_df.dropna()

,Brand,Store Number,Store Name,Ownership Type,Street Address,City,State/Province,Country,Postcode,Phone Number,Timezone,Longitude,Latitude
11964,Starbucks,3513-125945,Safeway-Anchorage #1809,Licensed,5600 Debarr Rd Ste 9,Anchorage,AK,US,995042300,907-339-0900,GMT-09:00 America/Anchorage,-149.78,61.21
11965,Starbucks,74352-84449,Safeway-Anchorage #2628,Licensed,1725 Abbott Rd,Anchorage,AK,US,995073444,907-339-2800,GMT-09:00 America/Anchorage,-149.84,61.14
11966,Starbucks,12449-152385,Safeway - Anchorage #1813,Licensed,1501 Huffman Rd,Anchorage,AK,US,995153596,907-339-1300,GMT-09:00 America/Anchorage,-149.85,61.11
11967,Starbucks,24936-233524,100th & C St - Anchorage,Company Owned,"320 W. 100th Ave, 100, Southgate Shopping Ctr ...",Anchorage,AK,US,99515,(907) 227-9631,GMT-09:00 America/Anchorage,-149.89,61.13
11968,Starbucks,8973-85630,Old Seward & Diamond,Company Owned,1005 E Dimond Blvd,Anchorage,AK,US,995152050,907-344-4160,GMT-09:00 America/Anchorage,-149.86,61.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...
25567,Starbucks,74385-87621,Safeway-Laramie #2466,Licensed,554 N 3rd St,Laramie,WY,US,820723012,307-721-5107,GMT-07:00 America/Denver,-105.59,41.32
25568,Starbucks,73320-24375,Ridley's - Laramie #1131,Licensed,3112 E. Grand,Laramie,WY,US,820705141,307-742-8146,GMT-07:00 America/Denver,-105.56,41.31
25569,Starbucks,22425-219024,Laramie - Grand & 30th,Company Owned,3021 Grand Ave,Laramie,WY,US,82070,307-742-3262,GMT-07:00 America/Denver,-105.56,41.31
25570,Starbucks,10849-103163,I-80 & Dewar Dr-Rock Springs,Company Owned,118 Westland Way,Rock Springs,WY,US,829015751,307-362-7145,GMT-07:00 America/Denver,-109.25,41.58
25571,Starbucks,10769-102454,Coffeen & Brundage Lane-Sheridan,Company Owned,2208 Coffeen Ave,Sheridian,WY,US,828016213,307-672-5129,GMT-07:00 America/Denver,-106.94,44.77

In [4]:
# check dataframe counts
us_locations_df.count()

Brand             13608
Store Number      13608
Store Name        13608
Ownership Type    13608
Street Address    13608
City              13608
State/Province    13608
Country           13608
Postcode          13607
Phone Number      13122
Timezone          13608
Longitude         13608
Latitude          13608
dtype: int64

In [5]:
# Identify nearest city for each starbucks lat, lng combination
cities = []
store_number =[]
for index, row in us_locations_df.iterrows():
    city = citipy.nearest_city(row[11], row[12]).city_name
    cities.append(city)
    store_number.append(row[1])

In [6]:
# check the type of cities
type(cities)

list

In [7]:
# build dataframe
starbucks_city_df = pd.DataFrame(zip(store_number,cities),columns=['Store Number', 'City'])

In [8]:
# check type to be sure we created dataframe
type(starbucks_city_df)

pandas.core.frame.DataFrame

In [9]:
# title case on city
starbucks_city_df['City'] = starbucks_city_df['City'].str.title()

In [10]:
# take a peak that the cleaned city names
starbucks_city_df

       Store Number            City
0       3513-125945     Port Alfred
1       74352-84449     Port Alfred
2      12449-152385     Port Alfred
3      24936-233524     Port Alfred
4        8973-85630     Port Alfred
...             ...             ...
13603   74385-87621  Port Elizabeth
13604   73320-24375  Port Elizabeth
13605  22425-219024  Port Elizabeth
13606  10849-103163  Port Elizabeth
13607  10769-102454     Port Alfred

[13608 rows x 2 columns]

In [11]:
#Export the starbucks city data to csv
output_data_file = "Clean_Data/starbucks_cities.csv"
starbucks_city_df.to_csv(output_data_file, index = None, header=True)